### ISSUE TITLE
Why didn't continue to develop this project? 

### ISSUE THREAD

**Issue by taomin597715379** [solovev/gopsd#5]
It's a great honor to see your project on GitHub. I just want to know why didn't continue to develop this project?

**Comment by taomin597715379** [comment]
At present, we use a CGO Library of ImageMagick in the golang project. We want to develop a pure golang image processing graph to complete the daily image compression, watermark, format conversion, vector graph processing and other functions

**Comment by solovev** [comment]
Hi! The reason is very common - I just don't have time for this project, and in its current state it solved my problems (export layers, read typeTool data)

**Comment by taomin597715379** [comment]
Got it
